-- APP.ADOCOES definição

-- Drop table

-- DROP TABLE APP.ADOCOES;

CREATE TABLE APP.ADOCOES (
	ID INTEGER  PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	TIPO VARCHAR(100) NOT NULL,
	IDADE INTEGER NOT NULL,
	RACA VARCHAR(100) NOT NULL,
	STATUSADOCAO VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	IMAGEMURL VARCHAR(255) NOT NULL
);